package Constants;

public enum Commands {
    SIGNUP,
    LOGIN,
    LOGOUT,
    DISPLAY_MY_FLIGHTS,
    ADD_FLIGHT,
    CANCEL_FLIGHT,
    ADD_FLIGHT_DETAILS,
    DELETE_FLIGHT,
    DISPLAY_FLIGHTS,
    PERSIST_FLIGHTS,
    PERSIST_USERS,
    INVALID_COMMAND
}
